### ISSUE TITLE
rules-edit description-replace or append

### ISSUE THREAD

**Issue by itskeyes** [cpainchaud/pan-configurator#101]
Surrounding the string with quotes, the tool is still treating a ":" colon and other special characters as an end of statement/esacpe.

`rules-edit.php actions=description-append:"string: test;"`

**Comment by swaschkut** [comment]
":" and "/" are separator in the actions part, there is no plan to implement to escape these two characters.

the following is working:
`rules-edit.php 'actions=description-append:string test;'`
