### ISSUE TITLE
pa_rule-edit action:user-Set fatal error

### ISSUE THREAD

**Issue by Dapacruz** [cpainchaud/pan-configurator#102]
First of all, thank you for an amazing set of tools!

I am trying to add an LDAP user group to some rules and am getting the following fatal error. I searched the source and could not find the function (setUser). Is this something that could be easily implemented?

**Command used:**
pa_rule-edit in=api://panorama location=all ruletype=Security 'actions=user-Set:ACL_Windows_Servers' 'filter=((user has.regex "Infra Server - Windows Level 2") and (user has.regex "Infra Server - Windows Level 3")) and !(user has.regex "ACL_Windows_Servers")'

**Fatal error:**
Uncaught Error: Call to undefined method SecurityRule::API_setUser() in /pan-configurator/pan-configurator/utils/common/actions-rule.php:3280

**Stack trace:**
#0 /pan-configurator/pan-configurator/utils/common/actions.php(81): {closure}(Object(RuleCallContext))
#1 /pan-configurator/pan-configurator/utils/rules-edit.php(847): CallContext->executeAction(Object(SecurityRule))
#2 Command line code(1): require_once('/p...')
#3 {main}

**Comment by cpainchaud** [comment]
@swaschkut please have a look!  :)

**Comment by swaschkut** [comment]
thanks for remembering me.
I need to check it in detail, both methods setUser() and API_setUser() are not available.
this is shooting for an implementation
