### ISSUE TITLE
reluctant to upgrade

### ISSUE THREAD

**Issue by PaloGreg** [cpainchaud/pan-configurator#104]
Hello, Christophe:  

It has been many years since our previous contact during my time as resident engineer at palo.  Since then, I have been silently addicted to your rules-edit utility for the hundreds of palo migrations that I have performed since.  

I am still using your release from April 25 2017, and I am deathly afraid of upgrading something that works so well on my Macbook.  Unfortunately, recent client requirements have forced me onto Expedition instead the old and reliable Migration Tool.  Now, the first time I need to tweak a config before loading into Panorama, I am getting runtime errors.  If you tell me I must upgrade your code, I will bite the bullet, but if the issue is caused by Expedition then upgrading is pointless.  Thank you for your time and your contributions!  

Runtime errors are pasted below:

 php /Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/utils/rules-edit.php in=MT-EnbGreen.xml out=output2.xml location=any actions=logSetting-set:Log_Forwarding_Panorama

***********************************************
************ RULE-EDIT UTILITY ****************

 - Detected platform type is 'panos'
 - No 'ruleType' specified, using 'security' by default
 - Loading configuration through PAN-Configurator library... 
* ** ERROR ** * Died on user notice or warning!! Error: Trying to get property of non-object on /Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/lib/rule-classes/class-NatRule.php:195

 *** Backtrace ***
0 ****
       derr()
       ::/Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/lib/panconfigurator.php line 77
1 ****
       myErrorHandler()
       ::/Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/lib/rule-classes/class-NatRule.php line 195
2 ****
   PANConf: / VirtualSystem:vsys1 / RuleStore:NAT / NatRule:Rule 3
       NatRule::load_from_domxml() @
           /Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/lib/rule-classes/class-RuleStore.php line 149
3 ****
   PANConf: / VirtualSystem:vsys1 / RuleStore:NAT
       RuleStore::load_from_domxml() @
           /Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/lib/device-and-system-classes/class-VirtualSystem.php line 254
4 ****
   PANConf: / VirtualSystem:vsys1
       VirtualSystem::load_from_domxml() @
           /Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/lib/device-and-system-classes/class-PANConf.php line 258
5 ****
   PANConf:
       PANConf::load_from_domxml() @
           /Users/spacemonkey/Desktop/AIS/palo-alto/pan-configurator/utils/rules-edit.php line 555

**Comment by swaschkut** [comment]
Hi,
What you can easily do is:
1) Download the latest available commit form this repo (Feb 2019).
2) export it to a different system or virtuell system
3) run your command there for validation

It is hard from here to validate, what is wrong in your old installation.

FYI:
this repro was updated last in Feb 2019, the forked repro:
https://github.com/swaschkut/pan-configurator was last updated in Sep 2019

The framework itself is right now handled in a different way as before.
If you need more help, please ping via [firstname]@[surname].de

regards
Sven
Waschkut
