### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in 

### ISSUE THREAD

**Issue by jjmtz70** [cpainchaud/pan-configurator#106]
I haven't used panconfigurator in years and not sure what I am doing wrong this is happening on Ubuntu 20, I al getting tis fatal error:  PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in 

Full command:

juanjo@virtuosa:~/pan/pan-configurator/utils$ php rules-edit.php in=amsdc1-defgw_LSC_Part.xml out=output.xml actions=display 'filter=action.is.deny'

***********************************************
************ RULE-EDIT UTILITY ****************

PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /home/juanjo/pan/pan-configurator/lib/panconfigurator.php on line 54
PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /home/juanjo/pan/pan-configurator/lib/panconfigurator.php on line 61
PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /home/juanjo/pan/pan-configurator/lib/panconfigurator.php on line 68

**PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in** /home/juanjo/pan/pan-configurator/utils/rules-edit.php:363
Stack trace:
#0 {main}
  thrown in /home/juanjo/pan/pan-configurator/utils/rules-edit.php on line 363
juanjo@virtuosa:~/pan/pan-configurator/utils$

**Comment by jjmtz70** [comment]
Sorry I had not installed php-xml and php-curl.

**Comment by swaschkut** [comment]
As you may also have seen, the development of pan-configurator on this repository stopped years ago.

Please check news about the progress on https://github.com/swaschkut/pan-configurator
