### ISSUE TITLE
exportToExcel - negate addresses

### ISSUE THREAD

**Issue by echickering** [cpainchaud/pan-configurator#38]
I used your exportToExcel and changed extension to HTML. We have some policies with negated addresses but there is no reference of them being negated in export. There a method of adding "Negate" for source/destination objects referenced?

**Comment by cpainchaud** [comment]
what do you think about adding a field in the excel file named "negated source" and "negated dest" ?

**Comment by echickering** [comment]
Works for me

**Comment by cpainchaud** [comment]
implemented
