### ISSUE TITLE
address-edit.php - how to recursively enumerate content of an address group

### ISSUE THREAD

**Issue by nikmat1** [cpainchaud/pan-configurator#41]
I'm trying to work out a syntax of "address-edit.php" to list all address objects (names, IPv4 values and description) contained within  an address group with a given name. Ideally it should be recursive (i.e. understand if a group is contained within the target group). Is this possible at all?

So far the best I could do was this:

`php address-edit.php in=api://<ip-address> location=any actions=exportToExcel:objects.xls,whereused "filter=(object is.ip-netmask) or (object is.ip-range) or (object is.fqdn)"`

And then I use Excel to filter all objects by the name of the group they are used in. This is not ideal and I feel there is a better way of achieving the same even without programming.

Can somebody help? 

To put this question into a context - my end goal is to convert address group to EDL.

**Comment by cpainchaud** [comment]
Hi,

get latest version and try that:
pa_address-edit in=tmp.xml out=/dev/null actions=exportToExcel:test.html,whereused|resolveIP 'filter=(object is.group)' location=any

**Comment by nikmat1** [comment]
Brilliant! Thanks a lot for fixing this so quickly!!!
I need to do more extensive testing but it's already very close to being perfect for my use case.

Though I had to quote actions otherwise Windows takes the vertical bar as a pipe and stops with _"'resolveIP' is not recognized as an internal or external command"_

The syntax below works for me:

```
php address-edit.php in=api://<firewall-ip-address> location=any actions="exportToExcel:objects.xls,whereused|resolveIP" "filter=(object is.group) and (name eq <address group name>)"
```

**Comment by cpainchaud** [comment]
yes, you have to quote the actions both in Windows or Unix , it's considered as special character for shells in general

**Comment by nikmat1** [comment]
Chris,

It appeared that I got too optimistic too early :)
Further testing revealed that this does not work well in fact. 
The way the Excel file gets populated is wrong in two senses (in the context of my end goal of converting Address Group to EDL):

1. All cells in Location, Name, Type, Description and Tags columns are merged which is bad (though Value and IP Resolution use one line/cell per entry which is good). It would make much more sense to repeat location/name/type/description/tags in each line so that the file looked as follows (example):

`vsys1 | group1 | group-static | address-object1 | description-of-group1 | tags-of-group1 | where-used | ip-resolution-of-address-object-1
vsys1 | group1 | group-static | address-object2 | description-of-group1 | tags-of-group1 | where-used | ip-resolution-of-address-object-2
vsys1 | group1 | group-static | address-object3 | description-of-group1 | tags-of-group1 | where-used | ip-resolution-of-address-object-3` 

2. On top of #1 the column "value" is then sorted alphabetically (names of all address objects within the target address group) and at the same time the column "ip resolution" is also _independently_ sorted alphabetically - this totally breaks the link between individual address objects and their values (IP addresses).

I hope I explained the issue clearly enough (let me know if not - I could email you some screenshots to explain the issue better).

As long as the above is sorted this would make the resulting Excel file suitable for further manipulations using native Excel tools (i.e. Data -> Filter, export to other formats and cut/paste to other editors i.e. Notepad++) and thus produce a nice looking EDL at the end.

Another great improvement would be to also include not only IP address of the address objects but their description as well.

**Comment by cpainchaud** [comment]
yes please come with a screenshot because cells are not supposed to be merged and they are not merged in my own tests

**Comment by nikmat1** [comment]
I pinged you a question on LinkedIn (hope you do not mind)
On 27 Feb 2017, at 12:19, Christophe <notifications@github.com<mailto:notifications@github.com>> wrote:

yes please come with a screenshot because cells are not supposed to be merged and they are not merged in my own tests
