### ISSUE TITLE
address-edit.php - how to recursively enumerate content of an address group (re-opening)

### ISSUE THREAD

**Issue by nikmat1** [cpainchaud/pan-configurator#42]
_It appeared that I cannot re-open a closed issue so posting this as a new one..._

Chris,

It appeared that I got too optimistic too early :)
Further testing revealed that this does not work well in fact.
The way the Excel file gets populated is wrong in two senses (in the context of my end goal of converting Address Group to EDL):

1)  All cells in Location, Name, Type, Description and Tags columns are merged which is bad (though Value and IP Resolution use one line/cell per entry which is good). It would make much more sense to repeat location/name/type/description/tags in each line so that the file looked as follows (example):

`vsys1 | group1 | group-static | address-object1 | description-of-group1 | tags-of-group1 | where-used | ip-resolution-of-address-object-1`
`vsys1 | group1 | group-static | address-object2 | description-of-group1 | tags-of-group1 | where-used | ip-resolution-of-address-object-2`
`vsys1 | group1 | group-static | address-object3 | description-of-group1 | tags-of-group1 | where-used | ip-resolution-of-address-object-3`

2)   On top of #1 the column "value" is then sorted alphabetically (names of all address objects within the target address group) and at the same time the column "ip resolution" is also independently sorted alphabetically - this totally breaks the link between individual address objects and their values (IP addresses).

I hope I explained the issue clearly enough (let me know if not - I could email you some screenshots to explain the issue better).

As long as the above is sorted this would make the resulting Excel file suitable for further manipulations using native Excel tools (i.e. Data -> Filter, export to other formats and cut/paste to other editors i.e. Notepad++) and thus produce a nice looking EDL at the end.

Another great improvement would be to also include not only IP address of the address objects but their description as well.

Regards,
Nikolay

**Comment by cpainchaud** [comment]
I think I understand what you mean.

unfortunately, this is an "exportToExcel" feature, it's not meant to make EDLs , at least exactly the way you want them. My script does resolve all objects then aggregates their IP together to merge contiguous networks. that makes sense for people who want to 'see' what IPs are covered by a group.

You need to go for a customer script / address-edit plugin to achieve exactly what you want.
