### ISSUE TITLE
tag-edit enhancement

### ISSUE THREAD

**Issue by netdiver80** [cpainchaud/pan-configurator#43]
Can we get a feature to set the tag color with tag-edit?

**Comment by swaschkut** [comment]
tag-edit.php actions=setColor:[color] is now available.
For available colors please check "tag-edit.php listactions"

===============================================
* setColor                  | #1 color:string         | *nodefault* | none,red,green,blue,yellow,copper,orange,purple,gray,light green,cyan,light gray,blue gray,lime,black,gold,brown,dark green
===============================================
