### ISSUE TITLE
Enhancement to pa_rules-edit

### ISSUE THREAD

**Issue by fwphil** [cpainchaud/pan-configurator#44]
pa_rules-edit allows in the list of actions the ability to set the securityProfile-Group-Set. Some users want to set the individual security profiles on a number of rules spread through a policy using the filters. 

Can we enhance the securityProfile-Gropup set to allow individual security profiles to be applied to rules ?

**Comment by cpainchaud** [comment]
implemented in recent commit https://github.com/cpainchaud/pan-configurator/commit/93aeffb146a052b33c50ac141ca26f0697b741c4
