### ISSUE TITLE
Attempting to add a tag to all service objects without any current tags

### ISSUE THREAD

**Issue by ozzie657** [cpainchaud/pan-configurator#50]
Is there a null value that I can filter on for service tags?

pa_service-edit in=api://XXXX actions=display location=any "filter=(tag has NULL)"

Not sure how I can apply those either as listActions for service doesn't have any options for tag modifications. The options exist for object, but not for services.

I'd rather not apply a tag to each of those objects manually as there are quite a few thousand that I am migrating.

Any help would be greatly appreciated.

**Comment by swaschkut** [comment]
just introduced the following actions and filters

service-edit: new actions tag-Add | tag-Add-Force | tag-Remove | tag-Remove-All | tag-Remove-Regex
service-edit: new filter tag has / has.nocase / has.regex and tag.count >,<,=,!

**Comment by cpainchaud** [comment]
@ozzie657 please use filter  (tag.count = 0) that Sven just added for you.


Have a nice day !

**Comment by ozzie657** [comment]
Thanks for the epic response time!!
