### ISSUE TITLE
description-Append - new line

### ISSUE THREAD

**Issue by bethatasitmay** [cpainchaud/pan-configurator#63]
Hi:

As far as I know, currently the description-Append action only adds text immediately following any existing text.  I would like to be able to add a new line as we put in ticket numbers each time we change a rule with each ticket on its own line.

Thanks!

**Comment by swaschkut** [comment]
Hi,

Please find this feature introduced in the last commit.

example usage:
pa_rule-edit in=api://[DEVICE-IP] 'actions=description-append:TEST,yes' 'filter=(name eq [RULENAME])'
