### ISSUE TITLE
description-Append - prepending a space

### ISSUE THREAD

**Issue by bethatasitmay** [cpainchaud/pan-configurator#64]
Hi:

Whenever I run a description-Append action it prepends the entire description with a space (in other words, it puts a space at the very beginning of the description).  If I do multiple runs against the same rule it keeps adding a space.

Thanks!

**Comment by swaschkut** [comment]
Hi,

Please find this feature introduced in the last commit.

example usage:
pa_rule-edit in=api://[DEVICE-IP] 'actions=description-append:TEST,yes' 'filter=(name eq [RULENAME])'
