### ISSUE TITLE
rule-edit add 'has.only' filter for service

### ISSUE THREAD

**Issue by netdiver80** [cpainchaud/pan-configurator#68]
It would be nice to have a 'has.only' filter for service with pa_rule-edit.

**Comment by cpainchaud** [comment]
Ok but on which field?

**Comment by netdiver80** [comment]
'service' field 

filter='(service has.only tcp-1341)'

**Comment by cpainchaud** [comment]
Please check latest code, I have added it.

**Comment by patrickwillekens** [comment]
Bonjour Christophe,

Peux tu m’expliquer comment je peux metre le code a jour ?
Il y a t’il un howto ?
Je travaille sur Mac.

Bien a toi

Patrick

**Comment by patrickwillekens** [comment]
Christophe,

You can forget previous mail, I found it
Sorry for the inconvenience, I thought there was a special procedure, but it just downloading the latest version.

Patrick

From: Patrick Willekens <pwillekens@paloaltonetworks.com>
Date: Monday, 28 August 2017 at 09:56
To: cpainchaud/pan-configurator <reply@reply.github.com>
Subject: Mise a jour

                Bonjour Christophe,

Peux tu m’expliquer comment je peux metre le code a jour ?
Il y a t’il un howto ?
Je travaille sur Mac.

Bien a toi

Patrick
