### ISSUE TITLE
filter for URL-category

### ISSUE THREAD

**Issue by nikmat1** [cpainchaud/pan-configurator#70]
Christophe,

Would it be possible to add "URL-category" to the list of available filters in rules-edit.php?

The use case for us it to be able to tag rules according to their matching criteria. For example we tag as follows:

(L4)
====
php rules-edit.php in=api://<...> location=any actions=tag-Add-Force:(L4),none stats "filter=((app is.any) and (service has.regex /[A-Z,a-z,0-9,\-,\_,\ ,\.]/ ))"

(L7)
====
php rules-edit.php in=api://<...> location=any actions=tag-Add-Force:(L7),none stats "filter=(!(app is.any))"

URL-category is the only criterion that is currently missing :(

It would also be fantastic to be able to filter by standard characteristics of the app(s) (i.e. Category/Subcategory/Technology/Risk/Characteristic). The use case for us is to be able to identify rules affecting SaaS applications in particular (in attempt to put in order currently disordered big security rule sets with hundreds of rules for Internet access along).

Thanks a ton in advance. 

BTW Fantastic job with all these script - massively helpful in automation.

Regards,
Nikolay

**Comment by cpainchaud** [comment]
Hi @nikmat1 

new filters have been added : (url.category is.any)  and (url.category has adult)

**Comment by cpainchaud** [comment]
new filters: rules-edit: new filter 'app technology.is', 'app category.is', 'app subcategory.is' just commited

**Comment by nikmat1** [comment]
This is brilliant. I really appreciate such a quick response and the solution.
The only thing missing from app filter is "characteristic" (SaaS, Evasive, Transfers Files, Excessive Bandwidth etc.) - would that be possible to add it as well?

**Comment by cpainchaud** [comment]
Hi, please have a look at latest commits and do some trial then let us know  #74

**Comment by nikmat1** [comment]
Christophe,

It seems to be working very well on our panorama config. What I did not get is why you had deviated from standard terminology used in pan-os and applipedia; and why you made "charasteristic" syntax different from _risk_, _technology_, _subcategory_ and _category_.

What if we stick to the same syntax and spelling there? So that the app filter looked as follows:

* app
    - has
    - has.nocase
    - is.any
    - **category.is**
    - **subcategory.is**
    - **technology.is**
    - **risk.is**
    - **_charactristic.is_**

**_Characteristic_** would then accept values as follows:
    - evasive
    - excessive-bandwidth
    - prone-to-misuse
    - saas
    - transfers-files
    - tunnels-other-apps
    - used-by-malware
    - vulnerabilities
    - widely-used

This way the filter would look way more consistent, aligned to standard Palo classification and thus easy to memorize and use.

**Comment by cpainchaud** [comment]
good point.

since characteristics can have multiple values enabled, I suggest we go for 'app characteristic.**has** xxxx' rather than characteristic.**is**

**Comment by swaschkut** [comment]
Characteristic.has with multiple arguments I expect.


These are the additional available content for apps at the predefined.xml file:
- is.virus.ident
- is.file.forward
- is.file.type.ident

**Comment by cpainchaud** [comment]
Hi Nikolay,

Branch "1.5_appfilter_characteristic.is" is almost ready to be published if you wanna give it a try before we merge with master. (app characteristic.has xxxx) has been implemented and is replacing other filters

**Comment by nikmat1** [comment]
.has sounds good - I did not think about multiple characteristics and thought the same could actually be achieved by specifying "and" in the filter (i.e. _(app charcateristic.is saas) and  (app charcateristic.is evasive)_).

What are the possible values for _characteristic_ then? I tried the aforementioned saas and evasive and they worked like a charm but then tries "transfers-files" and did not get no matches nor an error message. The has to be a sanity check for what is entered; and possible values have to be shown on the "listfilters" help screen.

**Comment by cpainchaud** [comment]
if you input a characteristic that does not exist then you should get an error message like that:

> * ** ERROR ** * Characteristic named 'file-transfers' does not exist. Supported values are: evasive,excessive-bandwidth,prone-to-misuse,saas,transfers-files,tunnels-other-apps,used-by-malware,vulnerabilities,widely-used

I found a typo in the code for file-transfer so it was not detecting them properly, it should work now.
We have plans to enhance listFilters / HTML help, it's a bigger question outside of this scope.

virus.ident, file.forward, file.type.ident are internal (not publicly displayed) properties.

**Comment by nikmat1** [comment]
It works now! Thank you.

BTW how do I use multiple values for characteristics? Comma or space separation does not seem to work.

**Comment by cpainchaud** [comment]
it doesn't support multiple characteristics : it would be unclear if that filter would be a 'OR' or a 'AND'.

I am currently working on a addition filters. something like 'app characteristic.has.all.from.list xxx,yyy' or I could develop an Application Query system and you would use a subquery as you can find some for 'source' and 'destination' field

**Comment by cpainchaud** [comment]
remember that filter is applied to every single app of the rules, so chaining several filters on app could select rules with several apps, each of them matching one of your criteria.

**Comment by nikmat1** [comment]
ok, I see. understood.

BTW - let me know if you need any help with documentation; 
perhaps I could produce something nice looking (i.e. a PDF) if you give me raw data

**Comment by cpainchaud** [comment]
if you look in utils/doc/  there is an HTML file that gets autogenerated. The plan is to enhance that for fitlers

**Comment by nikmat1** [comment]
yes, this doc is good, the only problem is that it does not contain anything for the scripts... neither the right syntax nor examples...

**Comment by cpainchaud** [comment]
we're open to suggestions. I think you should start by naming issues you've found / infos you could not find and then propose a way to address that

**Comment by cpainchaud** [comment]
in the meantime, everything is merged in Master now. The branch is now deleted

**Comment by nikmat1** [comment]
Christophe,

After further testing I discovered that "characteristic" filter does not work correctly in all cases. 
Some examples:

1. When a security rule has "linkedin-mail" explicitly listed among applications in a rule - the script matches this rule
2. When a security rule has an application filter defined as "Subcategory - email" (which "linkedin-email" is a member of, the **script does not match the rule**
3. When a security rule has a container application (i.e. "webex") the **script does not match the rule** (if any of "sub" applications such as "webex-base" or "webex-chat" are explicitly listed then the script does match the rule) 

Regards,
Nikolay

**Comment by swaschkut** [comment]
Hi Nikolay,
regarding your last comment:

- to 2) - PAN-OS app-objects “Application Filter” and “Application Group” are not implemented in pan-configurator yet

- to 3) - “application-container” from predefined.xml is not yet available in pan-configurator.

All this is on the ToDo list for the next further big release.
But there is no timeline available when this will happen.

regards
Sven

**Comment by nikmat1** [comment]
Understood. I'm sorry to hear that - this would have been invaluable feature.

**Comment by cpainchaud** [comment]
actually containers are supported but we are testing some fixes that should be available today.

ApplicationGroups are not yet in

**Comment by swaschkut** [comment]
Hi Nikolay,

Branch '1.5_application-group_introduction' contains BETA code to handle application-group and application-filter.

Please be aware that for application-filter there is still some limitations available:
If multiple choices are done for category, subcategory, technology or risk only the last choice is really filtered out.

example:
If you have a filter for category with 1) collaboration and 2) networking,
only networking is used for this application-filter.

I look forward to get feedback from you.

regards
Sven

**Comment by nikmat1** [comment]
Thank you Sven. I will test and give you a feedback.
On 20 Sep 2017, at 15:51, Sven Waschkut <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Nikolay,

Branch '1.5_application-group_introduction' contains BETA code to handle application-group and application-filter.

Please be aware that for application-filter there is still some limitations available:
If multiple choices are done for category, subcategory, technology or risk only the last choice is really filtered out.

example:
If you have a filter for category with 1) collaboration and 2) networking,
only networking is used for this application-filter.

I look forward to get feedback from you.

regards
Sven

**Comment by swaschkut** [comment]
application-filter is fully supported with latest commit to Branch '1.5_application-group_introduction'

**Comment by nikmat1** [comment]
Sorry for going silent for a while - I had no opportunity to test.

The filter seems to be capturing all container apps now - thank you very much!
