### ISSUE TITLE
support for container applications in "app" filter

### ISSUE THREAD

**Issue by nikmat1** [cpainchaud/pan-configurator#77]
May I suggest another improvement?

It would be really useful if app "has/has.nocase" could understand container apps too. For example if I have a rule that contains "ms-lync-audio" it should be captured by the filter that contains "ms-lync"; and in opposite direction too - i.e. if I specify "ms-office365-base" or "ms-powerbi" or "ms-teams" in the filter it would also trigger on the rules which have the container app "ms-office365".

**Comment by nikmat1** [comment]
And another improvement necessary for the app filter is an ability to identify custom applications, and in particular the ones which do not have signatures defined (and thus rely purely on L4 override rules).

**Comment by swaschkut** [comment]
let me put this on the TODO list.

**Comment by swaschkut** [comment]
can you please check the new app filters in branch 1.5_application-group_introduction

- (app includes.full.or.partial ms-lync-audio) => match for ms-lync
[ms-lync includes ms-lync-audio]
- (app included-in.full.or.partial ms-lync) => match for ms-lync-audio
[ms-lync-aduio is included-in ms-lync] (and all other app from
app-container ms-lync)

- (app includes.full.or.partial ms-teams) => match for ms-office365
- (app included-in.full.or.partial ms-office365) => match for ms-teams
(and all other apps from app-container ms-office365)

As soon as I have finalized the code validation against other pan-c framework related projects I will merge this to master branch

**Comment by swaschkut** [comment]
all merged to master branch

for custom application with signature this new filter is available:
pa_rule-edit in=check-appid.xml out=/dev/null actions=display 'filter=(app custom.has.signature)'

your feedback is appritiated

**Comment by cfrank18** [comment]
Can I sued below script to view unused object-groups? I just want to see how many unused service  object groups I have




php service-edit.php in=2934.xml out=/dev/null actions=exportToExcel:Brm_A_objects.xls location=shared 'filter=((object is.unused) and ( object is.group)'
*************************************************************************
This e-mail may contain confidential or privileged information.
If you are not the intended recipient, please notify the sender immediately and then delete it.

TIAA
*************************************************************************

**Comment by swaschkut** [comment]
Can you please open a new issue next time and not use this one which is not related to your problem.
Thanks

I recommend to use “(object is.unused.recurisve)”, so that you do not get service groups which are used in other service groups.

php service-edit.php in=2934.xml out=/dev/null actions=exportToExcel:Brm_A_objects.xls location=shared 'filter=((object is.unused.recursive) and ( object is.group)'

**Comment by swaschkut** [comment]
implemented Nov 30
