### ISSUE TITLE
Initial install/connection 

### ISSUE THREAD

**Issue by rjdpatesting** [cpainchaud/pan-configurator#82]
Hi Guys, 

I hope ye are well. Trying to follow the pdf guide to get this connected to my firewall using a mac. 
Downloaded the repository, github for mac. Getting lost after part 1.5 on the instructions. 

Do we not have to add the adp user, api key and firewall ip in one of the files ? which file do we enter this in ?

https://live.paloaltonetworks.com/t5/API-Articles/PAN-Configurator-scripting-library-and-utilities/ta-p/52163/jump-to/first-unread-message

cheers

Rob

**Comment by cpainchaud** [comment]
firewall credentials will be prompted by the script when it needs them

**Comment by rjdpatesting** [comment]
Hi Mate, 

Which file do we use then or how do we point it towards the firewall address ? 

Appreciate the reply, 

Rob
