### ISSUE TITLE
Match all rules with ip

### ISSUE THREAD

**Issue by jochristian** [cpainchaud/pan-configurator#83]
Hi,

Would it be possible to use this tool to match all rules that match an specific ip or subnet.
Not necessarily an address object.

Example: 
I want to match all rules that would hit an ip of 1.1.1.1.  Even rules with (any, or 1.1.1.0/24).
Could also be searching for rule matching 192.168.10.0/24 (Even rules with any or 192.168.0.0/16).

I don't care about the order of the rules. I want to match everything.
Is this possible to achive?

/Jo Chr

**Comment by swaschkut** [comment]
please have a look at the available utils script:

pa_rule-edit in=api://[DEVICE MGMTIP] actions=display 'filter=( (src includes.full.or.partial 1.1.1.1) or (dst includes.full.or.partial 1.1.1.1) )'

pa_rule-edit in=api://[DEVICE MGMTIP] actions=display 'filter=( (src includes.full.or.partial 192.168.10.0/24) or (dst includes.full.or.partial 192.168.10.0/24) )'

I expect you like to filter only for SRC or for DST at the same time.

**Comment by jochristian** [comment]
Hi @swaschkut ,

Thanks for the tip.
This works for rules where an address object or the ip itself exist in the rule. But it does not seem to work for rules with source or destination any. 

I will look some more at the source code :-) 

/Jo Christian

**Comment by swaschkut** [comment]
hi,

maybe you can start with:
pa_rule-edit help

there you will also find more information like:
pa_rule-edit listfilters

In this output you can find something like (dst is.any) / (src is.any).

If you now combine the filters you like to have you get the expected output.

**Comment by jochristian** [comment]
Hello,

Yep, looking at this now.
Thanks again

**Comment by cpainchaud** [comment]
'filter=( (src includes.full.or.partial 192.168.10.0/24) or (src is.any) or (dst includes.full.or.partial 192.168.10.0/24) or (dst is.any) )'
