### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by bethatasitmay** [cpainchaud/pan-configurator#85]
Hi

I'm getting a TLS error when attempting to update on the git pull origin master.  Is this something on my end or on github's end?

C:\dev>update-pan-configurator.bat

C:\dev>SET PATH=<snip>

C:\dev>cd pan-configurator

C:\dev\pan-configurator>git stash
Saved working directory and index state WIP on master: 07cf6ae Merge pull reques
t #84 from cpainchaud/1.5_managedfirewall_extend_with_model
HEAD is now at 07cf6ae Merge pull request #84 from cpainchaud/1.5_managedfirewal
l_extend_with_model

C:\dev\pan-configurator>git clean -f

C:\dev\pan-configurator>git pull origin master
fatal: unable to access 'https://github.com/cpainchaud/pan-configurator.git/': e
rror:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

C:\dev\pan-configurator>pause
Press any key to continue . . .

**Comment by swaschkut** [comment]
have you tried using:

update-pan-configurator-invalid-ssl.bat

**Comment by bethatasitmay** [comment]
Same thing:

C:\dev>update-pan-configurator-invalid-ssl.bat

C:\dev>SET PATH=<snip>

C:\dev>cd pan-configurator

C:\dev\pan-configurator>git stash
Saved working directory and index state WIP on master: 07cf6ae Merge pull reques
t #84 from cpainchaud/1.5_managedfirewall_extend_with_model
HEAD is now at 07cf6ae Merge pull request #84 from cpainchaud/1.5_managedfirewal
l_extend_with_model

C:\dev\pan-configurator>git clean -f

C:\dev\pan-configurator>git -c http.sslVerify=false pull origin master
fatal: unable to access 'https://github.com/cpainchaud/pan-configurator.git/': e
rror:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

**Comment by swaschkut** [comment]
the git tools available within the dev.zip package were outdated.
I uploaded an updated version to https://app.box.com/v/pan-configurator where you can download the newest dev.zip file

**Comment by swaschkut** [comment]
windows package is updated with latest git client version
https://app.box.com/v/pan-configurator
