### ISSUE TITLE
Won't run after latest updates

### ISSUE THREAD

**Issue by bethatasitmay** [cpainchaud/pan-configurator#91]
I updated just now and started the console... 
[update-output.txt](https://github.com/cpainchaud/pan-configurator/files/2187369/update-output.txt)

And when I try to do even something simple like look to see if a rulename is in use I get the same error:

_pa_rule-edit in=api://panorama-fqdn location=any ruletype=security actions=display 'filter=(name contains pre-rule2343)'

***********************************************
************ RULE-EDIT UTILITY ****************

 - Downloading config from API... OK!
 - Detected platform type is 'panorama'
 - Rule filter after sanitization: (name contains pre-rule2343)
 - Loading configuration through PAN-Configurator library... PHP Catchable fatal error:  Argument 2 passed to DH::findFirstElement() must be an instance of DOMNode, boolean given, called in C:\dev\pan-configurator\lib\network-classes\class-IPsecTunnel.php on line 127 and defined in C:\dev\pan-configurator\lib\misc-classes\class-DH.php on line 127_

I also tried a rule export and got the same error output.

Just to confirm, everything was working fine prior to the update since I did a fresh install back in March.

**Comment by bethatasitmay** [comment]
If it matters, our Panorama instance is on v8.0.10.

**Comment by cpainchaud** [comment]
Sorry for the inconvenience, it looks like your IPsec tunnels have no <protocol> section in the XML for some of your ProxyIDs . Our automated checks don't have this use-case, we need to investigate

**Comment by cpainchaud** [comment]
The tool reads the whole config anyway, location argument is used later on to reduce the scope of the changes

I think you know it but you can revert to a previous commit in the meantime

**Comment by bethatasitmay** [comment]
Oh, right - sorry, I knew that - I've watched it run enough times, lol.

Revert or re-install?  If the former I wasn't aware of that.  How do I do that (feel free to point me to documentation if it's already written somewhere).

I will if I need to but in case you'd like me to test something I'll keep this version available (I can always have one of my peers run something for me in the short term).

**Comment by cpainchaud** [comment]
can you try latest update please ?

**Comment by bethatasitmay** [comment]
Updated (see update output below) but same error.

[update-output-20180712.txt](https://github.com/cpainchaud/pan-configurator/files/2190536/update-output-20180712.txt)

**Comment by swaschkut** [comment]
can please add the error output

**Comment by bethatasitmay** [comment]
Sorry, I should've just listed it instead of being somewhat vague with "same error."

~>pa_rule-edit in=api://panorama-fqdn location=any ruletype=security actions=display 'filter=(name contains pre-rule2347)'

***********************************************
************ RULE-EDIT UTILITY ****************


 - Downloading config from API... OK!
 - Detected platform type is 'panorama'
 - Rule filter after sanitization: (name contains pre-rule2347)
 - Loading configuration through PAN-Configurator library... **PHP Catchable fatal error:  Argument 2 passed to DH::findFirstElement() must be an instance of DOMNode, boolean given, called in C:\dev\pan-configurator\lib\network-classes\class-IPsecTunnel.php on line 127 and defined in C:\dev\pan-configurator\lib\misc-classes\class-DH.php on line 127**

**Comment by swaschkut** [comment]
Can you please recheck if you have the newest code.
There was another commit at 8pm CEST (UTC+2) yesterday

**Comment by bethatasitmay** [comment]
Oh, I don't have that and now I get an error trying to update:

error: Your local changes to the following files would be overwritten by merge:
        utils/rules-edit.php
Please commit your changes or stash them before you merge.
Aborting
Updating 39b00e1..c15030f

I did open rules-edit.php with Notepad++ but I'm 99% sure I didn't save the file.

Is there a way to tell the updater to overwrite or do I need to re-install?

**Comment by bethatasitmay** [comment]
I downloaded the dev.zip file again, ran the setup bat, and ran the updater but it failed:

C:\dev>update-pan-configurator.bat

C:\dev>SET PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Perl
64\site\bin;C:\Perl64\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbe
m;C:\Windows\System32\Windows System Resource Manager\bin;C:\Windows\idmu\common
;C:\Network\WinSCP\;C:\Program Files\OmniBack\bin\;C:\Windows\System32\WindowsPo
werShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\W
indowsPowerShell\v1.0\;C:\Program Files\Microsoft Office\root\Office16\;C:\Progr
am Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\
Network\Putty\;C:\Security\Nmap;C:\dev\php;C:\openssl;C:\openssl\bin;C:\Win32Ope
nSSL-Lite;C:\Win32OpenSSL-Lite\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program F
iles\Common Files\Intel\WirelessCommon\;C:\dev\php;C:\dev\Console2;C:\dev\git\bi
n

C:\dev>cd pan-configurator

C:\dev\pan-configurator>git -c user.name=test -c user.email=test@test.com stash

warning: LF will be replaced by CRLF in utils/address-edit.php.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in utils/rules-edit.php.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in utils/service-edit.php.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in utils/tag-edit.php.
The file will have its original line endings in your working directory.
Saved working directory and index state WIP on master: 80a6a08 Merge remote-trac
king branch 'cpainchaud/master'

C:\dev\pan-configurator>git clean -f

C:\dev\pan-configurator>git pull origin master
remote: Counting objects: 787, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 787 (delta 448), reused 466 (delta 438), pack-reused 307
Receiving objects: 100% (787/787), 3.56 MiB | 6.33 MiB/s, done.
Resolving deltas: 100% (643/643), completed with 161 local objects.
From https://github.com/swaschkut/pan-configurator
 * branch            master     -> FETCH_HEAD
   80a6a08..059d54f  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        utils/rules-edit.php
Please commit your changes or stash them before you merge.
Aborting
Updating 80a6a08..059d54f

C:\dev\pan-configurator>pause
Press any key to continue . . .

C:\dev\pan-configurator>

**Comment by cpainchaud** [comment]
Honestly I am confused your windows package is pointing to https://github.com/swaschkut/pan-configurator which a fork of this one (https://github.com/cpainchaud/pan-configurator)
Also another issue I see of that the .bat file is not the one I used to share.

I guess @swaschkut needs to double-check what he's changed in the Windows package

**Comment by swaschkut** [comment]
FYI:
the old windows package out of september 2017 is and was always available at this BOX folder:
https://app.box.com/v/pan-configurator
I moved this package now to a subfolder .../master which is available now with this direct link:
https://app.box.com/folder/51441876917

The problem with the git update can be solved with a "git reset --hard origin/master".
To make it easier I uploaded "update-github.bat" which does exactly this.

=> run update-pan-configurator.bat
if it fail:
=> run update-reset-github.bat

I tried to combine both commands into the update-pan-configurator.bat but without success.

**Comment by bethatasitmay** [comment]
I downloaded swaschkut's latest update and installed it to a new folder, ran the update batch file (which threw a ton of LF messages which prevented me from seeing any other messages above them), and then ran one of my commands that wasn't working before and it worked.

Somewhat related question out of curiosity: I see in the update VPN and interface related classes being removed.  Is that a "to be fixed" item or something else.

C:\dev\pan-configurator>git clean -f
Removing doc/class-Throwable.html
Removing lib/helper-classes/class-ServiceSrcPortMapping.php
Removing lib/network-classes/class-IKEGateway.php
Removing lib/network-classes/class-IKEGatewayStore.php
Removing lib/network-classes/class-IPSecCryptoProfil.php
Removing lib/network-classes/class-IPSecCryptoProfileStore.php
Removing lib/network-classes/class-IkeCryptoProfil.php
Removing lib/network-classes/class-IkeCryptoProfileStore.php
Removing lib/network-classes/class-TunnelIfStore.php
Removing lib/network-classes/class-TunnelInterface.php
Removing lib/network-classes/class-VlanIfStore.php
Removing lib/network-classes/class-VlanInterface.php
Removing lib/rule-classes/class-AuthenticationRule.php
Removing tests/input/panorama-8.1.xml
Removing utils/download_predefined.php

**Comment by swaschkut** [comment]
if you check your local git repository, all files are still available.

no class files were removed on the swaschkut/pan-configurator nor the cpainchaud/pan-configurator github project.

I will go ahead and close this issue.

**Comment by bethatasitmay** [comment]
Thanks again guys - please keep up the great work! :-)
