### ISSUE TITLE
** WARNING ** * interface configured objectname: x.x.x.x not found.

### ISSUE THREAD

**Issue by bethatasitmay** [cpainchaud/pan-configurator#95]
Hi:

I don't know for sure when this one started but I first noticed it after fixing my install issues recently (last week?) and I am updated as of a few minutes ago.

I have 2 templates out of 15 that are getting this error and these are both for standalone PA-500s running v8.0.

The warnings don't seem to be affecting anything and I was able to commit to the firewalls in question including  forced template commit.

While running what appears to be any pa_rule-edit command in the console I see these messages:

************ RULE-EDIT UTILITY ****************

 - Downloading config from API... OK!
 - Detected platform type is 'panorama'
 - Rule filter after sanitization: (name eq Rule-01)
 - Loading configuration through PAN-Configurator library...
* ** WARNING ** * interface configured objectname: 192.168.254.84 not found.

 *** Backtrace ***
0 ****
       mwarning()
       ::C:\dev\pan-configurator\lib\device-and-system-classes\class-VirtualSystem.php line 270
1 ****
   PanoramaConf: / Template:Template-1 / PANConf: / VirtualSystem:vsys1
       VirtualSystem::load_from_domxml() @
           C:\dev\pan-configurator\lib\device-and-system-classes\class-PANConf.php line 280
2 ****
   PanoramaConf: / Template:Template-1 / PANConf:
       PANConf::load_from_domxml() @
           C:\dev\pan-configurator\lib\device-and-system-classes\class-Template.php line 52
3 ****
   PanoramaConf: / Template:Template-1
       Template::load_from_domxml() @
           C:\dev\pan-configurator\lib\device-and-system-classes\class-PanoramaConf.php line 547
4 ****
   PanoramaConf:
       PanoramaConf::load_from_domxml() @
           C:\dev\pan-configurator\utils\rules-edit.php line 555
5 ****
       require_once()
       ::Command line code line 1

* ** WARNING ** * interface configured objectname: 192.168.254.85 not found.

 *** Backtrace ***
0 ****
       mwarning()
       ::C:\dev\pan-configurator\lib\device-and-system-classes\class-VirtualSystem.php line 270
1 ****
   PanoramaConf: / Template:Template-2 / PANConf: / VirtualSystem:vsys1
       VirtualSystem::load_from_domxml() @
           C:\dev\pan-configurator\lib\device-and-system-classes\class-PANConf.php line 280
2 ****
   PanoramaConf: / Template:Template-2 / PANConf:
       PANConf::load_from_domxml() @
           C:\dev\pan-configurator\lib\device-and-system-classes\class-Template.php line 52
3 ****
   PanoramaConf: / Template:Template-2
       Template::load_from_domxml() @
           C:\dev\pan-configurator\lib\device-and-system-classes\class-PanoramaConf.php line 547
4 ****
   PanoramaConf:
       PanoramaConf::load_from_domxml() @
           C:\dev\pan-configurator\utils\rules-edit.php line 555
5 ****
       require_once()
       ::Command line code line 1

OK! (2.86 seconds, 34.25 mb memory)

* processing ruleset 'PanoramaConf: / RuleStore:Security that holds 53 rules
* objects processed in DG/Vsys '' : 0 filtered over 53 available

**Comment by swaschkut** [comment]
last commit improve the IP Interface validation
