### ISSUE TITLE
tag-edit.php not support actions=exportToExcel

### ISSUE THREAD

**Issue by baxter888** [cpainchaud/pan-configurator#99]
Hello,

Can you implement in tag-edit.php the action exportToExcel.

regards
baxter888

**Comment by swaschkut** [comment]
Hi,

sorry for late response.
The merge today include the new action for tag-edit.php

pa_tag-edit in=api://[MGMT-IP] actions=exporttoExcel:[file.xls]

Please test and validate this new action.

regards
Sven
